site_name: Documentation SmartContest
site_description: Documentation utilisateur de SmartContest, la solution SaaS pour organiser vos compétitions sportives
site_author: Ineaweb
site_url: https://smartcontest.fr

# Repository
repo_name: Ineaweb/SmartContest
repo_url: https://github.com/Ineaweb/SmartContest

docs_dir: docs
site_dir: site

extra_css: [theme/smartcontest.css]

# Configuration
theme:
  name: material
  language: fr
  favicon: img/favicon.ico
  logo: img/logo-white.svg

  
  # Palette par défaut Material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair
    #     name: Passer en mode clair

  font:
    text: Poppins  

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

# Navigation
nav:
  - Accueil: index.md
  - Guide utilisateur:
    - Créer un compte: create-account.md
    - Acheter des crédits: buy-credit.md
    - Lier son compte à HelloAsso: link-helloasso.md
    - Créer une compétition: create-competition.md
    - Gestion d'une compétition:
      - work-with-competition/index.md
      - Configuration générale: work-with-competition/general-configuration.md
      - Gérer les aires de compétition: work-with-competition/manage-area.md
      - Gérer les arbitres: work-with-competition/manage-referee.md
      - Gérer les participants: work-with-competition/manage-participant.md
      - Gérer les matchs: work-with-competition/manage-contest.md
      - Gérer les affichages: work-with-competition/manage-display.md
      - Concevoir une compétition: work-with-competition/design-competition.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - footnotes

# Plugins
plugins:
  - mermaid2
  - search:
      lang: fr
